version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule: { interval: weekly, day: monday }
    open-pull-requests-limit: 5
    groups:
      androidx: { patterns: ['androidx.*'] }
      build-tools: { patterns: ['org.jetbrains.kotlin*', 'com.android.*', 'com.android.tools*'] }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
