changelog:
  exclude:
    labels: [skip-changelog]
    authors: [dependabot]
  categories:
    - title: 🔐 الأمان والخصوصية
      labels: [security, privacy]
    - title: ✨ ميزات جديدة
      labels: [enhancement, feature]
    - title: ⚡ الأداء
      labels: [performance]
    - title: 🐞 إصلاحات
      labels: [bug]
    - title: 🎨 التصميم والواجهة
      labels: [ui, design]
    - title: 🌐 اللغة والترجمة
      labels: [i18n]
    - title: 📦 تغييرات أخرى
      labels: ['*']
